import type { PrismaClient } from "@prisma/client";

const DAY = 24 * 60 * 60 * 1000;
let seeded = false;

export async function ensureDemoData(prisma: PrismaClient) {
  if (seeded) return;

  const sourceCount = await prisma.source.count();
  if (sourceCount > 0) {
    seeded = true;
    return;
  }

  const now = new Date();

  await prisma.source.createMany({
    data: [
      {
        id: "src-ministry-policy",
        name: "农业农村部公开信息",
        url: "https://www.moa.gov.cn/",
        type: "POLICY",
        country: "CN",
        crawlMethod: "WEB",
        crawlFrequency: "daily",
        trustLevel: 5,
        enabled: true,
        defaultReview: "PENDING_REVIEW",
        lastStatus: "success",
        lastCrawledAt: now,
      },
      {
        id: "src-equipment-news",
        name: "水产设备企业动态",
        url: "https://example.com/aquaculture-equipment",
        type: "EQUIPMENT",
        country: "CN",
        crawlMethod: "WEB",
        crawlFrequency: "daily",
        trustLevel: 4,
        enabled: true,
        defaultReview: "PENDING_REVIEW",
        lastStatus: "success",
        lastCrawledAt: now,
      },
      {
        id: "src-market-price",
        name: "水产品价格公开样本",
        url: "https://example.com/aquaculture-market",
        type: "MARKET",
        country: "CN",
        crawlMethod: "WEB",
        crawlFrequency: "daily",
        trustLevel: 4,
        enabled: true,
        defaultReview: "PENDING_REVIEW",
        lastStatus: "success",
        lastCrawledAt: now,
      },
      {
        id: "src-research-industry",
        name: "水产科研与产业观察",
        url: "https://example.com/aquaculture-research",
        type: "RESEARCH",
        country: "CN",
        crawlMethod: "RSS",
        crawlFrequency: "weekly",
        trustLevel: 4,
        enabled: true,
        defaultReview: "PENDING_REVIEW",
        lastStatus: "success",
        lastCrawledAt: now,
      },
    ],
  });

  await prisma.intelItem.createMany({
    data: [
      {
        sourceId: "src-research-industry",
        title: "AI 识别正在进入工厂化养殖巡检场景",
        slug: "ai-vision-aquaculture-inspection",
        aiSummary: "机器视觉与多模态识别正在被用于鱼群状态判断、摄食行为分析、水面异常提醒和养殖巡检辅助。对养殖企业来说，真正有价值的不是单点识别准确率，而是能否把识别结果接入投喂、水质和人员巡检流程，形成连续可追踪的管理闭环。",
        editorSummary: "AI 识别技术从实验室演示走向工厂化养殖巡检，关键在于与水质、投喂和人工巡检数据打通。",
        category: "AI_AQUACULTURE",
        tags: "AI识别,机器视觉,工厂化养殖",
        species: "海水鱼,对虾",
        equipment: "摄像头,边缘计算盒",
        region: "华南",
        status: "PUBLISHED",
        isFeatured: true,
        riskLevel: 1,
        sourceUrl: "https://example.com/aquaculture-ai-vision",
        sourcePublishedAt: new Date(now.getTime() - 1 * DAY),
        publishedAt: new Date(now.getTime() - 1 * DAY),
      },
      {
        sourceId: "src-equipment-news",
        title: "智能投喂设备从定时控制转向数据闭环",
        slug: "smart-feeding-data-loop",
        aiSummary: "新一代智能投喂系统不再只强调自动化投料，而是把摄食反馈、溶氧变化、水温、饲料成本和生长阶段组合为决策参数。设备厂商正在从硬件售卖转向数据服务，这会影响养殖场对设备采购和运营维护的判断。",
        editorSummary: "智能投喂的竞争点正在从硬件执行转向数据闭环和运营算法。",
        category: "SMART_EQUIPMENT",
        tags: "智能投喂,设备,数据闭环",
        species: "加州鲈,罗非鱼,海水鱼",
        equipment: "智能投喂机,传感器",
        region: "广东",
        status: "PUBLISHED",
        isFeatured: true,
        riskLevel: 1,
        sourceUrl: "https://example.com/smart-feeding",
        sourcePublishedAt: new Date(now.getTime() - 2 * DAY),
        publishedAt: new Date(now.getTime() - 2 * DAY),
      },
      {
        sourceId: "src-market-price",
        title: "高温季节水质监测与动保需求升温",
        slug: "summer-water-quality-animal-health",
        aiSummary: "随着高温季节到来，溶氧、氨氮、亚硝酸盐和弧菌风险成为养殖管理中的高频变量。水质监测设备、快速检测产品和动保服务会进入需求高峰，养殖场更关注预警及时性和处理方案的可执行性。",
        editorSummary: "高温季节推动水质监测和动保服务需求增加，预警与处置流程成为核心。",
        category: "ANIMAL_HEALTH",
        tags: "水质监测,动保,高温季节",
        species: "南美白对虾,草鱼",
        equipment: "水质传感器,快速检测盒",
        region: "华南",
        status: "PUBLISHED",
        isFeatured: false,
        riskLevel: 2,
        sourceUrl: "https://example.com/water-quality-health",
        sourcePublishedAt: new Date(now.getTime() - 3 * DAY),
        publishedAt: new Date(now.getTime() - 3 * DAY),
      },
      {
        sourceId: "src-ministry-policy",
        title: "深远海养殖装备与标准化方案继续受到关注",
        slug: "offshore-aquaculture-equipment-standardization",
        aiSummary: "深远海养殖正在从平台建设走向运营能力建设，网箱结构、管材系统、养殖规程、苗种适配和安全运维是落地中的关键环节。未来项目更需要把装备、养殖对象、海域条件和标准化操作方案放在一起评估。",
        editorSummary: "深远海养殖的下一阶段重点不只是装备建设，而是装备与养殖方案的协同。",
        category: "POLICY",
        tags: "深远海养殖,装备,标准化",
        species: "绿鳍马面鲀,红鳍笛鲷",
        equipment: "深水网箱,管材系统",
        region: "湛江",
        status: "PUBLISHED",
        isFeatured: false,
        riskLevel: 1,
        sourceUrl: "https://example.com/offshore-aquaculture-policy",
        sourcePublishedAt: new Date(now.getTime() - 4 * DAY),
        publishedAt: new Date(now.getTime() - 4 * DAY),
      },
      {
        sourceId: "src-research-industry",
        title: "饲料苗种价格波动推动养殖成本精细化核算",
        slug: "feed-seedling-cost-accounting",
        aiSummary: "饲料、苗种和动保投入仍然是养殖成本核算的核心变量。随着市场价格波动加大，养殖主体更需要记录投喂量、成活率、生长速度和出塘价格，形成单塘口或单网箱维度的收益测算。",
        editorSummary: "饲料苗种波动让养殖企业更重视精细化成本核算。",
        category: "FEED_SEEDLING",
        tags: "饲料,苗种,成本核算",
        species: "草鱼,对虾,罗非鱼",
        region: "华南",
        status: "PUBLISHED",
        isFeatured: false,
        riskLevel: 1,
        sourceUrl: "https://example.com/feed-seedling-cost",
        sourcePublishedAt: new Date(now.getTime() - 5 * DAY),
        publishedAt: new Date(now.getTime() - 5 * DAY),
      },
      {
        sourceId: "src-market-price",
        title: "水产品电商渠道更重视产地故事与稳定供应",
        slug: "aquatic-ecommerce-origin-supply",
        aiSummary: "水产品电商渠道正在从低价竞争转向品质、产地故事、冷链履约和稳定供应。对养殖企业而言，能否提供标准化规格、稳定批次和可追溯信息，会影响进入渠道的议价能力。",
        editorSummary: "水产品电商渠道对稳定供应和可追溯信息的要求提高。",
        category: "ECOMMERCE",
        tags: "电商渠道,冷链,可追溯",
        species: "海水鱼,对虾",
        region: "全国",
        status: "PUBLISHED",
        isFeatured: false,
        riskLevel: 1,
        sourceUrl: "https://example.com/aquatic-ecommerce",
        sourcePublishedAt: new Date(now.getTime() - 6 * DAY),
        publishedAt: new Date(now.getTime() - 6 * DAY),
      },
      {
        sourceId: "src-research-industry",
        title: "海外养殖设备市场关注节能与远程运维",
        slug: "overseas-aquaculture-equipment-remote-operation",
        aiSummary: "海外水产装备市场持续关注节能增氧、远程运维和自动化监控。对于国内设备企业来说，产品稳定性、售后响应和数据接口能力可能成为进入海外市场的重要门槛。",
        editorSummary: "海外设备市场正在把节能和远程运维作为重要评价指标。",
        category: "OVERSEAS",
        tags: "海外市场,设备,远程运维",
        equipment: "增氧设备,远程监控系统",
        region: "海外",
        status: "PUBLISHED",
        isFeatured: false,
        riskLevel: 1,
        sourceUrl: "https://example.com/overseas-aquaculture-equipment",
        sourcePublishedAt: new Date(now.getTime() - 7 * DAY),
        publishedAt: new Date(now.getTime() - 7 * DAY),
      },
      {
        sourceId: "src-market-price",
        title: "华南主养品种价格样本显示分化趋势",
        slug: "south-china-aquaculture-price-divergence",
        aiSummary: "公开样本显示，华南地区不同养殖品种的价格表现存在分化。草鱼等大宗淡水鱼更受终端消费和流通库存影响，对虾价格则更依赖规格、成活率和阶段性供应。价格观察需要结合地区、规格和市场类型判断。",
        editorSummary: "华南水产品价格需要按品种、规格和区域拆分观察，不能只看单一均价。",
        category: "PRICE_MARKET",
        tags: "价格观察,华南,行情",
        species: "草鱼,南美白对虾,罗非鱼",
        region: "华南",
        status: "PUBLISHED",
        isFeatured: false,
        riskLevel: 1,
        sourceUrl: "https://example.com/south-china-price",
        sourcePublishedAt: new Date(now.getTime() - 8 * DAY),
        publishedAt: new Date(now.getTime() - 8 * DAY),
      },
    ],
  });

  await prisma.priceObservation.createMany({
    data: [
      {
        sourceId: "src-market-price",
        species: "草鱼",
        region: "华南",
        market: "批发市场公开样本",
        price: 7.2,
        unit: "元/斤",
        observedAt: new Date(now.getTime() - 1 * DAY),
        sourceUrl: "https://example.com/price-grass-carp",
        status: "PUBLISHED",
        note: "样本型公开来源观察，不代表全市场实时价格。",
      },
      {
        sourceId: "src-market-price",
        species: "南美白对虾",
        region: "广东",
        market: "产地样本",
        price: 22,
        unit: "元/斤",
        observedAt: new Date(now.getTime() - 1 * DAY),
        sourceUrl: "https://example.com/price-shrimp",
        status: "PUBLISHED",
        note: "不同规格价格差异较大，仅作页面演示。",
      },
      {
        sourceId: "src-market-price",
        species: "罗非鱼",
        region: "海南",
        market: "公开报价样本",
        price: 5.8,
        unit: "元/斤",
        observedAt: new Date(now.getTime() - 2 * DAY),
        sourceUrl: "https://example.com/price-tilapia",
        status: "PUBLISHED",
        note: "样本型公开来源观察。",
      },
      {
        sourceId: "src-market-price",
        species: "加州鲈",
        region: "珠三角",
        market: "流通市场样本",
        price: 15.6,
        unit: "元/斤",
        observedAt: new Date(now.getTime() - 3 * DAY),
        sourceUrl: "https://example.com/price-bass",
        status: "PUBLISHED",
        note: "需结合规格与流通库存判断。",
      },
    ],
  });

  await prisma.topic.createMany({
    data: [
      {
        name: "AI 水产养殖",
        slug: "ai-aquaculture",
        description: "追踪 AI 识别、智能巡检、边缘计算和养殖决策辅助在水产场景中的应用。",
        tags: "AI识别,智能巡检,数据闭环",
        sponsored: false,
      },
      {
        name: "深远海养殖装备",
        slug: "offshore-aquaculture-equipment",
        description: "关注深水网箱、养殖平台、管材系统、标准化规程与海域适配问题。",
        tags: "深远海养殖,网箱,装备",
        sponsored: false,
      },
      {
        name: "价格与成本观察",
        slug: "price-cost-watch",
        description: "按品种、区域、规格和成本要素观察水产市场价格变化。",
        tags: "价格行情,成本核算,市场观察",
        sponsored: false,
      },
    ],
  });

  await prisma.adSlot.createMany({
    data: [
      {
        name: "首页侧栏合作位",
        page: "home",
        position: "sidebar",
        sizeHint: "responsive",
        enabled: true,
        label: "广告合作",
        content: "设备、饲料、苗种、动保企业可联系合作。支持产品案例、解决方案和行业白皮书展示。",
      },
      {
        name: "情报详情合作位",
        page: "intel-detail",
        position: "sidebar",
        sizeHint: "responsive",
        enabled: true,
        label: "产业合作",
        content: "面向水产产业链企业开放专题合作与品牌展示。",
      },
    ],
  });

  seeded = true;
}
